site_name: HAYASHI
repo_url: https://github.com/PabloVD/HAYASHI
docs_dir: docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs

nav:
- Home:
  - 'Overview' : "index.md"
  - 'Requisites': 'requisites.md'
  - 'Usage': 'usage.md'
  - 'Non-LCDM' : 'nlcdm.md'
  - 'Examples' : 'examples.md'
  - 'Citation' : 'citation.md'

markdown_extensions:
  - admonition 
